### ISSUE TITLE
not all expected modern JavaScript syntax supported

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1183]
## Summary

Noticed that some basic JavaScript syntax features seems to be breaking though they should already be supported, like [private class fields](https://github.com/tc39/proposal-private-fields) and [static blocks](https://github.com/tc39/proposal-class-static-block).

```js
// static blocks
class SlideViewer extends HTMLElement {
  static observedAttributes = ['slide'];

   //. ...
}

customElements.define('slide-viewer', SlideViewer);
```

```js
// private 
class Counter extends HTMLElement {
  #x = 0;

  clicked() {
    this.#x++;
    window.requestAnimationFrame(this.render.bind(this));
  }

  constructor() {
    super();
    this.onclick = this.clicked.bind(this);
  }

  connectedCallback() { this.render(); }

  static observedAttributes = ['slide'];

  render() {
    this.textContent = this.#x.toString();
  }
}
window.customElements.define('num-counter', Counter);
```

The result of running the build will throw an error from Rollup
```sh
bundling static assets...
TypeError: baseVisitor[type] is not a function
    at c (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:23:22)
    at base.ClassBody (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:435:5)
    at c (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:23:22)
    at base.Class (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:428:3)
    at c (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:23:22)
    at base.ClassDeclaration.base.ClassExpression (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:424:80)
    at c (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:23:22)
    at Object.skipThrough (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:180:37)
    at c (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:23:22)
    at base.Program.base.BlockStatement (file:///Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/acorn-walk/dist/walk.mjs:192:5) {
  code: 'PLUGIN_ERROR',
  plugin: 'greenwood-import-meta-url',
  hook: 'transform',
  id: '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/presenter-mode.js',
  watchFiles: [
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/.greenwood/758806547.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/.greenwood/1377133907.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/.greenwood/12042177.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/presenter-mode.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/slide-list.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/link-target.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/iframe-key-capture.js',
    '/Users/owenbuckley/Workspace/github/greenwood-starter-presentation/node_modules/greenwood-starter-presentation/dist/components/slide-viewer.js'
  ]
}
error Command failed with exit code 1.
```

> Here's a little repo with some of these features demonstrated - https://github.com/thescientist13/greenwood-ihtml/tree/latest-acorn-features

## Details

At the time of this writing these should all be Stage 4 in ECMA and supported in all browsers, so not sure what gives? 🤷‍♂️ 
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static#browser_compatibility
- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_properties#browser_compatibility

----

I notice we are inconsistently configuring Acorn with different flags, one still stuck in 2020!
- https://github.com/ProjectEvergreen/greenwood/blob/v0.30.0-alpha.6/packages/cli/src/lib/walker-package-ranger.js#L49
- https://github.com/ProjectEvergreen/greenwood/blob/v0.30.0-alpha.6/packages/cli/src/plugins/resource/plugin-standard-javascript.js#L46

We should probably make this a lib that can export that configuration everywhere.  Additionally, we should make sure that in places we are walking a JS AST, there's no chance we could be processing TS and thus breaking Acorn.

**Comment by thescientist13** [comment]
As an aside, I wonder if this actually is something Greenwood should support, in exposing it's internals like this, instead of #550 ?  I guess its a question of the lag between standards, and that standard showing up in the parsing tools, like Acorn (JS) and CSSTree (CSS).  🤔

**Comment by thescientist13** [comment]
Doing some research yielded these related results
- https://github.com/acornjs/acorn/issues/1231
- https://github.com/rollup/rollup/issues/4250
- https://github.com/rollup/rollup/pull/4249

Which seem to indicate that as of [>= v2.79.0](https://github.com/rollup/rollup/commit/ce3de491b8ff0f61789c1ab61287ca06c9d19382#diff-2bc7d7ce54116db22884b732c3b26f3ebc5af8d3f4fddab5bc2d4b5a7ce12839), Rollup should be supporting, so not sure what gives?  I made sure to add a resolution to my project and confirm the latest `2.x` version of Rollup is installed in this project and also tried manually setting the ECMA version in [_rollup.config.js_](https://github.com/ProjectEvergreen/greenwood/blob/v0.29.0/packages/cli/src/config/rollup.config.js#L208)
```js
const ast = this.parse(await response.text(), { ecmaVersion: 'latest' });
```

```sh
➜  greenwood-starter-presentation git:(enhancement/issue-25-remove-lit-dependency) ✗ yarn why rollup
yarn why v1.22.19
[1/4] 🤔  Why do we have the module "rollup"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "rollup@2.79.1"
info Reasons this module exists
   - "@greenwood#cli" depends on it
   - Hoisted from "@greenwood#cli#rollup"
info Disk size without dependencies: "6.46MB"
info Disk size with unique dependencies: "6.46MB"
info Disk size with transitive dependencies: "6.46MB"
info Number of shared dependencies: 0
✨  Done in 0.11s.
```

I'm not sure if #1087 will help with this, though I think they [switched to SWC in v3](https://rollupjs.org/plugin-development/#this-parse)?  Would be good to test this out there.

Putting this code into the current version of their [REPL](https://rollupjs.org/repl/?pr=4249&shareable=JTdCJTIyZXhhbXBsZSUyMiUzQSUyMiUyMiUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJjb2RlJTIyJTNBJTIyY29uc3QlMjB0ZW1wbGF0ZSUyMCUzRCUyMGRvY3VtZW50LmNyZWF0ZUVsZW1lbnQoJ3RlbXBsYXRlJyklM0IlNUNuJTVDbnRlbXBsYXRlLmlubmVySFRNTCUyMCUzRCUyMCU2MCU1Q24lMjAlMjAlM0NzdHlsZSUzRSU1Q24lMjAlMjAlMjAlMjBpZnJhbWUlMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwd2lkdGglM0ElMjA5MCUyNSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBoZWlnaHQlM0ElMjA3MDBweCUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjBmaWx0ZXIlM0ElMjBkcm9wLXNoYWRvdyg1cHglMjAxMHB4JTIwM3B4JTIwZ3JheSklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCUzQyUyRnN0eWxlJTNFJTVDbiU1Q24lMjAlMjAlM0NpZnJhbWUlM0UlM0MlMkZpZnJhbWUlM0UlNUNuJTYwJTNCJTVDbiU1Q25jbGFzcyUyMFNsaWRlVmlld2VyJTIwZXh0ZW5kcyUyMEhUTUxFbGVtZW50JTIwJTdCJTVDbiUyMCUyMHN0YXRpYyUyMG9ic2VydmVkQXR0cmlidXRlcyUyMCUzRCUyMCU1QidzbGlkZSclNUQlM0IlNUNuJTVDbiUyMCUyMGNvbnN0cnVjdG9yKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwc3VwZXIoKSUzQiU1Q24lMjAlMjAlMjAlMjB0aGlzLnNsaWRlJTIwJTNEJTIwJTdCJTdEJTNCJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwY29ubmVjdGVkQ2FsbGJhY2soKSUyMCU3QiU1Q24lMjAlMjAlMjAlMjBpZiUyMCghdGhpcy5zaGFkb3dSb290KSUyMCU3QiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLmF0dGFjaFNoYWRvdyglN0IlMjBtb2RlJTNBJTIwJ29wZW4nJTIwJTdEKSUzQiU1Q24lMjAlMjAlMjAlMjAlMjAlMjB0aGlzLnNoYWRvd1Jvb3QuYXBwZW5kQ2hpbGQodGVtcGxhdGUuY29udGVudC5jbG9uZU5vZGUodHJ1ZSkpJTNCJTVDbiUyMCUyMCUyMCUyMCU3RCU1Q24lMjAlMjAlN0QlNUNuJTVDbiUyMCUyMGF0dHJpYnV0ZUNoYW5nZWRDYWxsYmFjayhuYW1lJTJDJTIwb2xkVmFsdWUlMkMlMjBuZXdWYWx1ZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwaWYlMjAobmFtZSUyMCUzRCUzRCUzRCUyMCdzbGlkZSclMjAlMjYlMjYlMjBuZXdWYWx1ZSklMjAlN0IlNUNuJTIwJTIwJTIwJTIwJTIwJTIwdGhpcy5zbGlkZSUyMCUzRCUyMEpTT04ucGFyc2UobmV3VmFsdWUpJTNCJTVDbiUyMCUyMCUyMCUyMCUyMCUyMHRoaXMucmVuZGVyKCklM0IlNUNuJTIwJTIwJTIwJTIwJTdEJTVDbiUyMCUyMCU3RCU1Q24lNUNuJTIwJTIwcmVuZGVyKCklMjAlN0IlNUNuJTIwJTIwJTIwJTIwdGhpcy5zaGFkb3dSb290LnF1ZXJ5U2VsZWN0b3IoJ2lmcmFtZScpLnNldEF0dHJpYnV0ZSgnc3JjJyUyQyUyMHRoaXMuc2xpZGUucm91dGUpJTNCJTVDbiUyMCUyMCU3RCU1Q24lN0QlNUNuJTVDbmN1c3RvbUVsZW1lbnRzLmRlZmluZSgnc2xpZGUtdmlld2VyJyUyQyUyMFNsaWRlVmlld2VyKSUzQiU1Q24lMjIlMkMlMjJpc0VudHJ5JTIyJTNBdHJ1ZSUyQyUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTdEJTVEJTJDJTIyb3B0aW9ucyUyMiUzQSU3QiUyMm91dHB1dCUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTdEJTdEJTdE) seems to work at least 👀 
<img width="1440" alt="Screenshot 2023-11-09 at 8 44 46 PM" src="https://github.com/ProjectEvergreen/greenwood/assets/895923/354d221a-147b-4090-b505-4b1ccad2dfa4">

As a work around if someone really needed to, they could probably use our [Babel plugin](https://github.com/ProjectEvergreen/greenwood/tree/v0.29.0/packages/plugin-babel) (or create their own using esbuild, SWC, etc) that should work as a stop gap.

Or if doing something like Web Compnents, just the getter version
```js
static get observedAttributes() {
  return ['slide'];
}
```

I think this is actually an acorn issue, as I see there is this repo for what appears to be the features we're looking for
https://github.com/acornjs/acorn-stage3

So not sure if we just need to add that for now?
