### ISSUE TITLE
getting a `Cannot read properties of null (reading 'rawAttrs')` error

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#1353]
## Type of Change

Bug

## Summary

In this project it was observed that at times [this line](https://github.com/ProjectEvergreen/greenwood/blob/v0.30.2/packages/cli/src/lib/layout-utils.js#L215) in Greenwood would fail in [this project](https://github.com/thescientist13/HP_Stuff/pull/1)
```sh
TypeError: Cannot read properties of null (reading 'rawAttrs')
    at getAppLayout (file:///Users/owenbuckley/Workspace/github-forks/HP_Stuff/node_modules/.pnpm/@greenwood+cli@0.31.0-alpha.1_patch_hash=pkl2llrpdlpyhjjur27kchnsuq/node_modules/@greenwood/cli/src/lib/layout-utils.js:221:66)
    at async StandardHtmlResource.serve (file:///Users/owenbuckley/Workspace/github-forks/HP_Stuff/node_modules/.pnpm/@greenwood+cli@0.31.0-alpha.1_patch_hash=pkl2llrpdlpyhjjur27kchnsuq/node_modules/@greenwood/cli/src/plugins/resource/plugin-standard-html.js:125:12)
    at async file:///Users/owenbuckley/Workspace/github-forks/HP_Stuff/node_modules/.pnpm/@greenwood+cli@0.31.0-alpha.1_patch_hash=pkl2llrpdlpyhjjur27kchnsuq/node_modules/@greenwood/cli/src/lifecycles/serve.js:69:27
    at async file:///Users/owenbuckley/Workspace/github-forks/HP_Stuff/node_modules/.pnpm/@greenwood+cli@0.31.0-alpha.1_patch_hash=pkl2llrpdlpyhjjur27kchnsuq/node_modules/@greenwood/cli/src/lifecycles/serve.js:55:5
```

## Details

Not really sure why so will need to play around with exactly why to find a reproduction case, but this simple fix seemed to work at least
```js
const mergedHtml = pageRoot && pageRoot.querySelector('html')?.rawAttrs
  ? `<html ${pageRoot.querySelector('html').rawAttrs}>`
  : appRoot.querySelector('html').rawAttrs !== ''
    ? `<html ${appRoot.querySelector('html').rawAttrs}>`
    '<html>';
```

All the pages in question seemed to have an `<html>` tag though?

**Comment by thescientist13** [comment]
So the reproduction was simply a page file with no `<html>` tag
```html
<body>
  <h3>Home Page</h3>
  <p>Coffey was here</p>
</body>
```
