### ISSUE TITLE
same unit test failing consistently, inconsistently on CircleCI

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#213]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
The tests have started failing consistently inconsistently recently (at least within the release/0.4.0 branch).

First it was this one
https://github.com/ProjectEvergreen/greenwood/pull/195#pullrequestreview-289849840
https://circleci.com/gh/ProjectEvergreen/greenwood/644
```
 5 failing

  1) Build Greenwood With: 
       Custom Webpack Plugin and Default Workspace
         Running Smoke Tests: Custom Webpack Plugin and Default Workspace
           Index (Home) page
             should have a <title> tag in the <head>:

      AssertionError: expected 'My App' to equal 'Greenwood App'
      + expected - actual

      -My App
      +Greenwood App
      
      at Context.<anonymous> (test/smoke-test.js:86:29)

  2) Build Greenwood With: 
       Custom Webpack Plugin and Default Workspace
         Running Smoke Tests: Custom Webpack Plugin and Default Workspace
           Index (Home) page
             should have the correct route tags in the <body>:

      AssertionError: expected 0 to equal 3
      + expected - actual

      -0
      +3
      
      at Context.<anonymous> (test/smoke-test.js:109:37)

  3) Build Greenwood With: 
       Custom Webpack Plugin and Default Workspace
         Running Smoke Tests: Custom Webpack Plugin and Default Workspace
           Index (Home) page
             should have the expected heading text within the index page in the public directory:
     TypeError: Cannot read property 'textContent' of null
      at Context.<anonymous> (test/smoke-test.js:113:64)

  4) Build Greenwood With: 
       Custom Webpack Plugin and Default Workspace
         Running Smoke Tests: Custom Webpack Plugin and Default Workspace
           Index (Home) page
             should have the expected paragraph text within the index page in the public directory:
     TypeError: Cannot read property 'textContent' of null
      at Context.<anonymous> (test/smoke-test.js:119:65)

  5) Build Greenwood With: 
       Custom Webpack Plugin and Default Workspace
         Running Smoke Tests: Custom Webpack Plugin and Default Workspace
           Hello World (dummy) page
             "before each" hook for "should output a hello page directory":
     Error: ENOENT: no such file or directory, open '/root/repo/packages/cli/test/cases/build.plugins-webpack/public/hello/index.html'
```

And then more failures, but all different test, but the same ones every time (there is some overlap in failure between the last ones)
- https://circleci.com/gh/ProjectEvergreen/greenwood/664
- https://circleci.com/gh/ProjectEvergreen/greenwood/666
- https://circleci.com/gh/ProjectEvergreen/greenwood/670
- https://circleci.com/gh/ProjectEvergreen/greenwood/671
- https://circleci.com/gh/ProjectEvergreen/greenwood/673

<img width="1559" alt="Screen Shot 2019-09-26 at 9 47 13 PM" src="https://user-images.githubusercontent.com/895923/65736772-38971b80-e0aa-11e9-8c28-d398b0c5e7bb.png">

## Details
```shell
  332 passing (3m)
  2 failing

  1) Build Greenwood With: 
       Default Greenwood Configuration and Default Workspace w/ Nested Directories
         Custom blog page directory
           should have the expected heading text within the hello example page in the hello directory:

      AssertionError: expected 'Greenwood' to equal 'Blog Page'
      + expected - actual

      -Greenwood
      +Blog Page
      
      at Context.<anonymous> (packages/cli/test/cases/build.default.workspace-nested/build.default.workspace-nested.spec.js:61:28)

  2) Build Greenwood With: 
       Default Greenwood Configuration and Default Workspace w/ Nested Directories
         Custom blog page directory
           should have the expected paragraph text within the hello example page in the hello directory:

      AssertionError: expected 'This is the home page built by Greenwood. Make your own pages in src/pages/index.js!' to equal 'This is the test blog page built by Greenwood.'
      + expected - actual

      -This is the home page built by Greenwood. Make your own pages in src/pages/index.js!
      +This is the test blog page built by Greenwood.
      
      at Context.<anonymous> (packages/cli/test/cases/build.default.workspace-nested/build.default.workspace-nested.spec.js:67:30)
```

**Comment by thescientist13** [comment]
So it looks like the issue that instead of custom values like the test is expecting, it looks like in the case of the title anyway, the default values from [_config.js_](https://github.com/ProjectEvergreen/greenwood/blob/release/0.4.0/packages/cli/src/lifecycles/config.js#L5) is showing, which means something isn't getting serialized correctly somewhere I guess?

**Comment by thescientist13** [comment]
phew, that was easy.  
<img width="1215" alt="Screen Shot 2019-09-26 at 10 17 15 PM" src="https://user-images.githubusercontent.com/895923/65737391-5d8c8e00-e0ac-11e9-91a4-03c22af5554f.png">

we can't use `async` in our mocha tests

**Comment by thescientist13** [comment]
@hutchgrant 
Hmm, now can't remember, is there a rule around `async` usage in our tests?  I see the usage in our `it` blocks inconsistently.  Wondering if that could be contributing to the issue?

**Comment by thescientist13** [comment]
Well, good news is that its reproducible in the Docker container following these steps
https://github.com/thegreenhouseio/docker-nodejs-dev#workflow

Ran `yarn test` twice and both times it failed with the exact same failure as the very first build failure observed 🚫 
https://circleci.com/gh/ProjectEvergreen/greenwood/644

Started testing some of these PRs
1. #216 : Ran this twice and it passed both times ✅ ✅ 
1. #215 : Ran this twice and it passed both times ✅ ✅  
1. release/0.4.0: Ran this twice again and it passed twice ✅ ✅ 
1. 😳 
1. Killed the container, started it again
1. release/0.4.0: Ran this twice again and it passed one, failed once ✅ 🚫  
```
326 passing (4m)
  8 failing
```

 🤷‍♂
