### ISSUE TITLE
similar query calls breaking production build with Invariant Violation 8 error

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#371]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
In my [website project](https://github.com/thegreenhouseio/www.thegreenhouse.io/pull/137), I have a [page template](https://github.com/thegreenhouseio/www.thegreenhouse.io/blob/technical/issue-133-markdown-for-blog-posts-bak/src/templates/post-template.js) template that is making its own `query` call.
```js
import { html, LitElement } from 'lit-element';
import client from '@greenwood/cli/data/client';
import gql from 'graphql-tag';

import '../components/blog-post/blog-post';
import '../components/footer/footer';
import '../components/header/header';
import '../components/navigation/navigation';
import pageCss from '../styles/page.css';
import '../styles/theme.css';

MDIMPORT;

class PostTemplate extends LitElement {
  ...

  async connectedCallback() {
    super.connectedCallback();
    let route = window.location.pathname;
    const response = await client.query({
      query: gql`query {
        graph {
          title,
          link,
          data {
            date,
            image
          }
        }
      }`
    });

    ...
  }

  ...
}

customElements.define('page-template', PostTemplate);
```

Results in an ApolloClient error
```
index.c10096742db3b816782b.bundle.js:1 Uncaught (in promise) Invariant Violation: Invariant Violation: 8 (see https://github.com/apollographql/invariant-packages)
    at new t (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:17113)
    at l (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:17334)
    at R (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:10323)
    at L (http://localhost:8000/index.c10096742db3b816782b.bundle.js:1:13986)
    at t.transformDocument (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:67607)
    at t.read (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:65761)
    at t.e.readQuery (http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:45766)
    at http://localhost:8000/index.c10096742db3b816782b.bundle.js:98:72246
```

![Screen Shot 2020-06-16 at 8 38 43 PM](https://user-images.githubusercontent.com/895923/84841805-6560d980-b011-11ea-88a9-8f87ea5307f7.png)

## Details
What I think correlation here is that since app-template is also making a `query` call for the graph, and this page template an adapted version of it, when logging _cache.json_, it looks like there are _two_ entries for the graph, one per call.  
![Screen Shot 2020-06-16 at 8 40 56 PM](https://user-images.githubusercontent.com/895923/84841905-ba9ceb00-b011-11ea-8ce2-ce7e2b653c4f.png)

Since it only happens in production, this is likely an issue with our [mock Apollo client](https://spectrum.chat/apollo/apollo-client/optimistic-response-failed-with-invariant-violation-8~9995b7e0-4cdd-42d1-9a50-2b3983079d2d).

**Comment by thescientist13** [comment]
Interesting observation that might not be an issue with _client.js_, it looks like in this situation, the _cache.json_ files themselves are empty?  😮 
![Screen Shot 2020-06-24 at 8 49 16 PM](https://user-images.githubusercontent.com/895923/85641322-3aebcd80-b65c-11ea-961f-e59c124b8968.png)

So this suggests something more fundamental in the CLI itself, for those files to end up empty in the first place... 🤔

**Comment by thescientist13** [comment]
Ok, now I think I know what is going on.  

It looks because both are graph calls, one is overwriting the other when we write all the queries to _cache.json_.  For example, I wasn't able to find my custom front-matter when looking in the generated file, only the graph data that was being requested from _app-template.js_.

Hoping this can be handled in _cache.js_ or similar.  🤞

**Comment by thescientist13** [comment]
Ok, so this helps.  Per [this comment]() was able to get some info about what the error message could mean
```
$ grep -r InvariantError node_modules/**/bundle.cjs.js
node_modules/apollo-client/bundle.cjs.js:      return Promise.reject(process.env.NODE_ENV === "production" ? new _tsInvariant.InvariantError(3) : new _tsInvariant.InvariantError('cache-only fetchPolicy option should not be used together with query refetch.'));
node_modules/apollo-client/bundle.cjs.js:      reject(process.env.NODE_ENV === "production" ? new _tsInvariant.InvariantError(8) : new _tsInvariant.InvariantError('QueryManager stopped while query was in flight'));
node_modules/apollo-client/bundle.cjs.js:      reject(process.env.NODE_ENV === "production" ? new _tsInvariant.InvariantError(16) : new _tsInvariant.InvariantError('Store reset while query was in flight (not completed in link chain)'));
node_modules/apollo-client/bundle.cjs.js:      throw process.env.NODE_ENV === "production" ? new _tsInvariant.InvariantError(1) : new _tsInvariant.InvariantError("In order to initialize Apollo Client, you must specify 'link' and 'cache' properties in the options object.\n" + "These options are part of the upgrade requirements when migrating from Apollo Client 1.x to Apollo Client 2.x.\n" + "For more information, please visit: https://www.apollographql.com/docs/tutorial/client.html#apollo-client-setup");
```

So this is what I should look into
```
node_modules/apollo-client/bundle.cjs.js:      reject(process.env.NODE_ENV === "production" ? new _tsInvariant.InvariantError(8) : new _tsInvariant.InvariantError('QueryManager stopped while query was in flight'));
```

**Comment by thescientist13** [comment]
Ok, I think (🤞 ) I finally know what is going on.  It makes a lot of sense now that I've had some chance to digest.  The crux of the issue is in the cache merging.  This is an issue because when there are multiple queries using the same top level root, e.g. `query`, when [`deepmerge` gets run during serialization on all the cache.json files](https://github.com/ProjectEvergreen/greenwood/blob/v0.7.1/packages/cli/src/lifecycles/serialize.js), it will return a single merged result of whatever the two respective queries are.  However, this "merged" response isn't going to match the query request since extra fields are going to be coming back it didn't expect.

It's just like in development, you get 1:1 request to response.  Now in prod, it's all joined together, which I think is where things start to break down.  Probably a naive optimizations / cleverness on my part to reconcile client / server cache handoff.  The shapes of query objects are slightly different in both contexts but there does appear to be a common structure.

----

So, what I think should be happening is to just drop the creation of a single merged _cache.json_.

Instead, just find a common way for both client and server to construct a hash of the query such that each unique query gets its own _{md5}-cache.json_ file.   This way, server can write the file and client can read the file and match each request to its intended response.
