### ISSUE TITLE
leverage NodeJS resolve logic for looking up location of paths for node modules

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#557]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
As part of looking into #505 as part of submitting #511 and so for then, was just getting something done that was quick and dirty, using unpkg.com as a fallback.  I'm not sure if this will support _everything_ like things added to `importMap`... but I did reach out in NodeJS slack channel and got this tip on using NodeJS [`require.resolve`](https://nodejs.org/api/modules.html#modules_require_resolve_request_options) and so that would certainly be interesting because if we could piggy back somehow of off Node's default resolve behavior, that would allow us to maintain all that on our own.

This would also ensure that when Greenwood is run from the command line using `npx`, _node_modules_ would always resolve correctly.

## Details
So essentially, give it a package name and it will look up the path for you.
```js
// /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/node_modules/es-module-shims/dist/es-module-shims.js
console.debug( require.resolve('es-module-shims') )
```

With a better local testing environment (using `npm|yarn link`), we could set it up so that it in **plugins-node-modules** `resolve` just delegates all this to `require.resolve` instead:
```js
// example url => /node_modules/es-module-shims/dist/es-module-shims.js
async resolve(url) {
  return new Promise((resolve, reject) => {
    try {
      const packageName = url.split('/')[1]; // ex. es-module-shims
      const packageFullPath = require.resolve(packageName); // ex. /Users/.../node_modules/es-module-shims/dist/es-module-shims.js
      const currentDirectory = packageFullPath.split('/node_modules/')[0]; //ex. /Users/.../
      const nodeModulesUrl = path.join(currentDirectory, url.replace.replace('/node_modules/'); //ex. /Users/.../es-module-shims/dist/es-module-shims.js

      resolve(nodeModulesUrl);
    } catch (e) {
      console.error(e);
      reject(e);
    }
  });
}
```

We might want to generate our own full path since the `url` is what we want based on walking _package.json_ (in theory) as opposed to what NodeJS _thinks_ we want.

----

Given that, perhaps there is a case for us to entirely refactor [`getPackageEntryPath`](https://github.com/ProjectEvergreen/greenwood/blob/master/packages/cli/src/plugins/resource/plugin-node-modules.js#L14) to be based off `require.resolve` logic instead? 🤔 

We intentionally always want to favor ESM if we can, so I guess it depends on if anything would break but we certainly have enough tests for that.  😃 

--- 

Another consideration might be around when to specify extensions being added to files, like the browser does, as currently right now for anything from _node_modules_ it is not required, but any components or JS in your project do.  Maybe a case for a plugin that will handle [resolving extensions a la webpack](https://webpack.js.org/configuration/resolve/#resolveextensions)?

**Comment by thescientist13** [comment]
As part of the WCWG, starting a repo for experimenting with this.
https://github.com/thescientist13/node-resolve-expirements

**Comment by thescientist13** [comment]
Will likely want to do an `alpha` release for this change and make sure to do tests for
- `npx`
- Stackblitz
- downstream projects

**Comment by thescientist13** [comment]
Cool, the `npx` steps from the home page work now without any of those [**unpkg** work arounds now](#505)!
<img width="1508" alt="Screen Shot 2021-09-10 at 5 41 41 PM" src="https://user-images.githubusercontent.com/895923/132920692-e720be8d-b27f-4451-89e7-c1ada2b2600e.png">

**Comment by thescientist13** [comment]
Observed as part of #716 that were still some critical hard coded paths assuming root level location of _node_modules, so will be re-opening this to try and clean those instances up.

**Comment by thescientist13** [comment]
Hmm, found a regression in a Lit@2 repo where `require.resolve` was not finding @types/trusted-types, but we had no proper fallback logic for that case
```sh
Unable to look up package using NodeJS require.resolve for => @types/trusted-types Error: Cannot find module '@types/trusted-types'
Require stack:
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lib/node-modules-utils.js
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lifecycles/config.js
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lifecycles/compile.js
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/commands/build.js
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at getNodeModulesResolveLocationForPackageName (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lib/node-modules-utils.js:7:42)
    at getPackageEntryPath (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:36:49)
    at /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:102:19
    at Array.forEach (<anonymous>)
    at walkPackageJson (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:98:47)
    at /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:186:9
    at Array.forEach (<anonymous>)
    at walkPackageJson (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js:98:47) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lib/node-modules-utils.js',
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/plugins/resource/plugin-node-modules.js',
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lifecycles/config.js',
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/lifecycles/compile.js',
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/commands/build.js',
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@greenwood/cli/src/index.js'
  ]
}
```


![Screen Shot 2021-09-20 at 5 15 52 PM](https://user-images.githubusercontent.com/895923/134078682-a815a8cb-1d8f-492c-8e5a-06bc1700b416.png)

it is a dependency of lit-html
```sh
% yarn why @types/trusted-types
yarn why v1.22.5
[1/4] 🤔  Why do we have the module "@types/trusted-types"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "@types/trusted-types@1.0.6"
info Reasons this module exists
   - "lit#lit-html" depends on it
   - Hoisted from "lit#lit-html#@types#trusted-types"
info Disk size without dependencies: "16KB"
info Disk size with unique dependencies: "16KB"
info Disk size with transitive dependencies: "16KB"
info Number of shared dependencies: 0
✨  Done in 0.54s.
```

----

Will try and narrow down why this is an issue now, but seems related to #725

**Comment by thescientist13** [comment]
Found found the root cause?  It seems that packages with [no main field](https://unpkg.com/browse/@babel/runtime@7.15.4/package.json) or an [empty main field](https://unpkg.com/browse/@babel/runtime@7.15.4/package.json) bomb out on usage of `require.resolve`.

```js
// index,js
require.resolve('@babel/runtime')
```

```sh
node index.js
LIT 111 /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/lit-html/lit-html.js
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/node_modules/@babel/runtime/package.json
    at throwExportsNotFound (internal/modules/esm/resolve.js:290:9)
    at packageExportsResolve (internal/modules/esm/resolve.js:513:3)
    at resolveExports (internal/modules/cjs/loader.js:432:36)
    at Function.Module._findPath (internal/modules/cjs/loader.js:472:31)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:867:27)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/index.js:3:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

```js
// index,js
require.resolve('@types/trusted-types');
```

```sh
% node index.js
Error: Cannot find module '@types/trusted-types'
Require stack:
- /Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.resolve (internal/modules/cjs/helpers.js:94:19)
    at Object.<anonymous> (/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/index.js:4:39)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/owenbuckley/Workspace/contributary/repos/www.contributary.community/index.js'
  ]
}
```

Maybe this is something that will be accounted for as part of ESM migration, by honoring export maps at least - #707
