### ISSUE TITLE
better support for invalid HTML (HTML forgiveness)

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#627]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [x] Improvement / Suggestion
- [ ] Bug
- [ ] Other (please clarify below)

## Summary
With the current HTML parser we are using, if invalid HTML is processed,
```html
<html>
  <head>
    <script type="module" src="../components/card/card.js"> <!-- no closing tag -->

  </head>
  <body>
    <!-- or tag isn't closed correctly -->
    <app-card><app-card>
  </body>
</html>
```

it will breaks in the terminal with a seemingly unrelated error in reference to a plugin.
```sh
  TypeError: Cannot read property 'innerHTML' of null
      at getAppTemplate (/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/plugins/resource/plugin-standard-html.js:61:42)
      at /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/plugins/resource/plugin-standard-html.js:318:16
      at new Promise (<anonymous>)
      at StandardHtmlResource.serve (/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/plugins/resource/plugin-standard-html.js:244:12)
      at /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/serve.js:87:49
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/serve.js:78:24
      at async /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/serve.js:78:24
      at async /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/serve.js:78:24
      at async /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/serve.js:78:24
```

## Details
What I believe to be happening is that [the parser](https://github.com/ProjectEvergreen/greenwood/blob/v0.13.0/packages/cli/src/plugins/resource/plugin-standard-html.js#L55) is erroring out so there is no HTML body for plugins to operate.  (presumably the value is `undefined`.  We should at minimum add some better error handling to better instruct / assist on how users can solve it.

**Comment by thescientist13** [comment]
This could / should also happen at the Rollup level?  For instance, something like forgetting to use `href` for a `<link>`
```html
<script type="module" src="/components/footer.js"></script>
<link rel="stylesheet" src="/styles/theme.css"></script>
```

will bomb out with a not very helpful message
```sh
TypeError: Cannot read property 'charAt' of undefined
    at /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/config/rollup.config.js:234:24
    at Array.forEach (<anonymous>)
    at Object.buildStart (/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/config/rollup.config.js:227:21)
    at /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/node_modules/rollup/dist/shared/rollup.js:18757:25
    at async Promise.all (index 1)
    at async rollupInternal (/Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/node_modules/rollup/dist/shared/rollup.js:19938:9)
    at async /Users/owenbuckley/Workspace/project-evergreen/repos/greenwood/packages/cli/src/lifecycles/bundle.js:2:172
```

Would be nice to say something like: _Oh, for a `<link>` tag you may have meant to use `href`_.  Since between `<script>` and `<link>` tags, it can be easy to confuse / forget the usage of `src` (`<script>`) and `href` (`<link>`) attributes.
