### ISSUE TITLE
TypeScript source maps are not found and are causing filesystem read error messages in development

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#661]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Testing **plugin-typescript** in a project and during development, noticing that the transpiled TypeScript appends a comment for source maps, but the dev server can't find them.

<img width="1657" alt="Screen Shot 2021-07-12 at 10 27 36 AM" src="https://user-images.githubusercontent.com/895923/125304808-e0bbba00-e2fb-11eb-96e2-1de50771ffee.png">

```js
GreetingComponent.styles = css `p { color: blue }`;
__decorate([
    property()
], GreetingComponent.prototype, "name", void 0);
GreetingComponent = __decorate([
    customElement('app-greeting')
], GreetingComponent);
export { GreetingComponent };
//# sourceMappingURL=module.js.map
```

Isn't breaking anything per se, other than looking a little ugly in the terminal.

```sh
% yarn develop
yarn run v1.12.3
$ greenwood develop
-------------------------------------------------------
Welcome to Greenwood (v0.14.0) ♻️
-------------------------------------------------------
Running Greenwood with the develop command.
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
Started local development server at localhost:1984

  Error: ENOENT: no such file or directory, open '/components/greeting/module.js.map'
      at Object.openSync (fs.js:476:3)
      at Object.readFileSync (fs.js:377:35)
      at /Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/plugins/resource/plugin-source-maps.js:23:30
      at new Promise (<anonymous>)
      at SourceMapsResource.serve (/Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/plugins/resource/plugin-source-maps.js:21:12)
      at /Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/lifecycles/serve.js:87:49
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/lifecycles/serve.js:78:24
      at async /Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/lifecycles/serve.js:78:24
      at async /Users/owenbuckley/Workspace/analogstudios.net/repo/www.analogstudios.net/node_modules/@greenwood/cli/src/lifecycles/serve.js:77:29
```

## Details
Not sure what the long term solution is but ideally would be nice to resolve to them somehow.  I think this may be meaningful to do as part of #658 perhaps though so I think for now
1. [ ] just make sure to check if the source map exists first
1. [ ] Keep this open and drop the _p0_ label and put into the next project along with #658

**Comment by thescientist13** [comment]
This is stale now per #1424
