### ISSUE TITLE
query string parameters in node_modules (CSS) paths returns no content and `204` response

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#690]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
As part of testing development of theme packs (#689) it was observed that when a CSS file was referenced [via an `import`](https://github.com/thescientist13/greenwood-starter-presentation/blob/master/src/components/presenter-mode.js#L2), e.g.
```js
import themeCss from '/node_modules/<package>/dist/theme.css?type=css';
```

<img width="1667" alt="Screen Shot 2021-08-07 at 5 15 27 PM" src="https://user-images.githubusercontent.com/895923/128614019-2380bc31-5087-407d-9b22-5565f096120f.png">

```sh
url /node_modules/greenwood-starter-presentation/dist/styles/theme.css?type=css

  TypeError: Cannot read property 'replace' of undefined
      at /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/plugin-import-css/src/index.js:33:50
      at new Promise (<anonymous>)
      at ImportCssResource.intercept (/Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/plugin-import-css/src/index.js:31:12)
      at /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:106:52
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:97:24
      at async /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:97:24
      at async /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:96:29
      at async /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:86:5
      at async /Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:49:5
```

In this case, The URL being passed to plugin-standard-css was still including the query string and thus failing the extension check, [since `path.extname`](https://github.com/ProjectEvergreen/greenwood/blob/v0.15.0/packages/cli/src/plugins/resource/plugin-standard-css.js#L21) was also including the query string `.css?type=css` and not just `.css`, and thus failing the test;
 

## Details
This [dovetails a little more into a discussion](https://github.com/ProjectEvergreen/greenwood/discussions/691) I opened to get a better handling on handling URLs and filesystem access, so will defer to that and so will just try and land a simple patch for this for now that tries to address the _resolver_ issue detailed in that discussion

After Greenwood resolvers go first, the results of those never get passed to next plugins, because we always pass the original URL to each resolvers, instead of saying forwarding the results of the node_modules resolver to any other resolvers that may want to reuse that logic.
```js
  ctx.url = await resources.reduce(async (responsePromise, resource) => {
    const response = await responsePromise;
    // const { url } = ctx; just keep using the resolved response
    const resourceShouldResolveUrl = await resource.shouldResolve(response);  // passing response here instead
    
    return resourceShouldResolveUrl
      ? resource.resolve(response) // passing response here instead
      : Promise.resolve(response);
  }, Promise.resolve(ctx.url));
```

Thus, in the above situation, with the existing code, the query string was always getting passed to plugin-standard-css and it wasn't able to handle that since we've never tested it with _node_modules_ paths + query strings.

**Comment by thescientist13** [comment]
I don't _think_ this is a regression as a result of the ordering of plugins changing in #520 but will look into it as part of the PR.
