### ISSUE TITLE
fetching JSON content (e.g. _graph.json_) or 404 files are breaking local dev E-Tag caching mechanism

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#908]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [x] Bug
- [ ] Other (please clarify below)

## Summary
Looks like a case was missed as part of #629 / #760 but it seems if a request comes in with `'Content-Type: application/json'` the project breaks with an error on the request.
```sh
% yarn develop
yarn run v1.22.5
$ greenwood develop
-------------------------------------------------------
Welcome to Greenwood (v0.24.0) ♻️
-------------------------------------------------------
Running Greenwood with the develop command.
Initializing project config
Initializing project workspace contexts
Generating graph of workspace files...
building from local sources...
Started local development server at localhost:1984
Unable to look up greenwood-starter-presentation using NodeJS require.resolve.
Unable to look up greenwood-starter-presentation using NodeJS require.resolve.
Unable to look up greenwood-starter-presentation using NodeJS require.resolve.
Unable to look up greenwood-starter-presentation using NodeJS require.resolve.

  TypeError: inputString.charCodeAt is not a function
      at hashString (file:///Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lib/hashing-utils.js:6:40)
      at file:///Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:141:26
      at dispatch (/Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/koa-compose/index.js:42:32)
      at file:///Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:125:11
      at async file:///Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:88:5
      at async file:///Users/owenbuckley/Workspace/github/repos/greenwood-starter-presentation/node_modules/@greenwood/cli/src/lifecycles/serve.js:51:5
```

![Screen Shot 2022-03-05 at 2 14 55 PM](https://user-images.githubusercontent.com/895923/156897069-06ef2900-0610-43bf-91f2-6c78571cf71c.png)

## Details
Seems to be because this logic passes `body` right to the hashing function
```js
const inm = ctx.headers['if-none-match'];
const etagHash = hashString(body);
```

But in the case of JSON, `body` is an Array, which means it wont have a `charAt` method since it is not a string.  A quick test shows this simple check can solve it.
```js
const etagHash = ctx.headers['content-type'].indexOf('application/json') >= 0
  ? hashString(JSON.stringify(body))
  : hashString(body);
```

Should probably add a test or figure out how to test for it.

**Comment by thescientist13** [comment]
Found another edge case, like with TypeScript sourcemaps which are currently not working, so have an empty body and should be excluded from trying to be E-Tag cached.
