### ISSUE TITLE
Runtime Strategies

### ISSUE THREAD

**Issue by thescientist13** [ProjectEvergreen/greenwood#953]
## Type of Change
- [ ] New Feature Request
- [ ] Documentation / Website
- [ ] Improvement / Suggestion
- [ ] Bug
- [x] Other (please clarify below)

## Summary
In preparation for [Serverless / Edge runtime](https://github.com/ProjectEvergreen/greenwood/discussions/626) support, want to use this to track any prep work needed to facilitate this.

## Details
Things to look out for
1. [ ] "Adapter" - Since serverless and Edge runtimes typically wont have things like `fs`
1. [ ] One off routes (on demand building API)

See #812 for reference

**Comment by thescientist13** [comment]
superseded by #1008

**Comment by thescientist13** [comment]
Still need this, separate from adapting for hosting platforms and providers.

**Comment by thescientist13** [comment]
So did some initial research on this by trying to "de" Node (🦕 ) WCC and while it seems `path.join` et al is mostly supplanted by `URL` now, the last big consideration I anticipated needing to solve for was `fs`.  My hope was that `fetch`, introducing into Greenwood via #957 would supplant this.

_However_, it appears that [`file://` URI types are not in the `fetch` spec](https://fetch.spec.whatwg.org/#scheme-fetch), left up to implementors to manage on their own.  
> _For now, unfortunate as it is, file: [URLs](https://url.spec.whatwg.org/#concept-url) are left as an exercise for the reader. 
 When in doubt, return a [network error](https://fetch.spec.whatwg.org/#concept-network-error).

Thus, support for it is inconsistent
- ⛔ [Node does not support it](https://github.com/nodejs/undici/pull/1239)
- ⛔ [**node-fetch** repo](https://github.com/node-fetch/node-fetch/issues/75#issuecomment-299755555) does not support
- ✅ [Deno](https://deno.land/manual@v1.28.3/runtime/web_platform_apis#fetching-local-files)
- ❓ Bun - TBD
- ❓ Workers - TBD
- ⚠️ [WINTERCG](https://github.com/wintercg/fetch/issues/4)

So we may need to support runtimes adapters in the short term it seems 🤕 

----

Some other related links
- https://github.com/sindresorhus/got/issues/227
- https://github.com/github/fetch/pull/92
- https://bugs.chromium.org/p/chromium/issues/detail?id=810400

**Comment by thescientist13** [comment]
Seems like a conversation around a standard `fs` implementation is in the works over at the WinterCG.

**Comment by thescientist13** [comment]
## Bun
Did a little testing with [Bun 1.0](https://bun.sh/blog/bun-v1.0).  Got an error related to importing **htmlparser**
```sh
116 | async function trackResourcesForRoute(html, compilation, route) {
117 |   const { context } = compilation;
118 |   const root = htmlparser.parse(html, {
                   ^
TypeError: htmlparser.parse is not a function. (In 'htmlparser.parse(html, {
    script: !0,
    style: !0
  })', 'htmlparser.parse' is undefined)
      at /Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/cli/src/lib/resource-utils.js:118:15
      at trackResourcesForRoute (/Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/cli/src/lib/resource-utils.js:116:38)
      at /Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/cli/src/lifecycles/prerender.js:121:10
      at /Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/cli/src/lifecycles/prerender.js:107:37
      at /Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/plugin-renderer-puppeteer/src/puppeteer-handler.js:19:18
      at /Users/owenbuckley/Workspace/project-evergreen/greenwood/packages/plugin-renderer-puppeteer/src/puppeteer-handler.js:13:23
      at processTicksAndRejections (:1:2602)
```

Made this change to the import and confirmed it worked in both Bun and Node and so was than able to succesfully build!
```js
# before
import htmlparser from 'node-html-parser';

# after
import * as htmlparser from 'node-html-parser';
```

However, it looks like the `serve` and `develop` commands work, but just show a white page 🤔 
![Screenshot 2023-09-11 at 8 44 47 PM](https://github.com/ProjectEvergreen/greenwood/assets/895923/94125ec7-a5db-4268-b181-098018cc7f67)

**Comment by thescientist13** [comment]
[npm specifiers are now available with Deno Deploy](https://github.com/denoland/deploy_feedback/issues/314#issuecomment-1708839169)

**Comment by thescientist13** [comment]
Not sure we'll be able to get this in for 1.0, so deferring to 1.x milestone.

**Comment by thescientist13** [comment]
I think now with Deno 2.0 and Bun, I bet a lot of this is sorted out now with npm, and so aside from just prefixing everything NodeJS specific with `:node` I bet it might just work!  🤞 

I think this item could still live on as a discussion to extricate the NodeJS parts at that point, but not sure how necessary it will be at that point.
